[package]
name = "rust-html-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen = "0.26.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true